oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8081

prisoner:
  search:
    endpoint.url: http://localhost:8093

offender:
  search:
    endpoint.url: http://localhost:8096

basm:
  endpoint.url: http://localhost:8097

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub